object Modules {
    const val app = ":app"

    const val core = ":core"
    const val coreDatabase = ":core-database"
    const val coreNetwork = ":core-network"
    const val composeUi = ":compose-ui"
    const val addMeal = ":feature:addmeal"
    const val search = ":feature:search"
    const val settings = ":feature:settings"
    const val mealPlanner = ":feature:mealplanner"
    const val kitchenTimer = ":feature:kitchen-timer"
    const val auth = ":feature:auth"
    const val homeData = ":feature:home:data"
    const val homeDomain = ":feature:home:domain"
    const val homePresentation = ":feature:home:presentation"
    const val homeDi = ":feature:home:di"
    const val searchData = ":feature:search:data"
    const val searchDomain = ":feature:search:domain"
    const val searchPresentation = ":feature:search:presentation"
    const val searchDi = ":feature:search:di"
    const val favoritesData = ":feature:favorites:data"
    const val favoritesDomain = ":feature:favorites:domain"
    const val favoritesPresentation = ":feature:favorites:presentation"
    const val favoritesDi = ":feature:favorites:di"
}