[versions]
kotlin = "1.8.21"
ksp = "1.8.21-1.0.11"
ktx = "1.9.0"
gradle = "8.0.0"
lifecycle = "2.5.1"
sqlDelight = "1.5.5"
ktor = "2.3.1"
koin = "3.2.0"
junit = "4.13.2"
coroutines = "1.6.4"
viewmodel-ktx = "2.5.1"
dagger-hilt = "2.46.1"
hilt-compiler = "1.0.0"
timber = "5.0.1"
desugar-jdk-libs = "2.0.0"
compose = "1.4.3"
compose-compiler = "1.4.7"
coil = "2.2.2"
compose-activity = "1.6.1"
compose-paging = "1.0.0-alpha12"
compose-livedata = "1.0.0-alpha07"
composeMaterial3 = "1.0.1"
navigation-compose = "1.0.0"
onebone = "2.3.5"
mixpanel = "7.2.2"
firebaseBom = "31.1.0"
qonversion-sdk = "4.2.0"
billing-version = "5.1.0"
accompanist = "0.27.0"
compose-destinations = "1.7.32-beta"

play-services-auth = "20.4.1"
hiltNavigationCompose = "1.0.0"
ktlint = "11.3.1"
google-services = "4.3.14"
multiplatformSettings = "1.0.0"
napier = "2.6.1"


play = "2.0.1"
one-tap = "1.0.3"
easycrop = "0.1.1"
paging = "3.1.1"
datastore = "1.0.0"
lottie = "5.2.0"
arch-core-testing = "2.1.0"
truth = "1.1.3"
leakcanary = "2.10"
searchable-dropdown = "0.2.7"
junit-ext = "1.1.5"
espresso-core = "3.5.1"
horizontal-calendar-view = "1.0.4"
core-splash-screen = "1.0.0"
material = "1.3.1"
appcompat = "1.6.0"
okhttp = "5.0.0-alpha.2"
chucker = "3.5.2"
firebase-auth-ktx = "21.0.2"
firebase-storage-ktx = "20.0.0"
firebase-database-ktx = "20.0.0"
material-icons-extended = "1.3.0"
compose-hilt-navigation = "1.0.0"
spotless = "5.17.1"
android-material = "1.8.0"
kotlinxSerialization = "1.2.2"
kotlinSerialization = "1.8.10"
kotlinxCoroutines = "1.6.0-native-mt"
kotlinxDateTime = "0.3.2"

[libraries]
androidx-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "ktx" }
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
junit = { group = "junit", name = "junit", version.ref = "junit" }

coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
coroutines-play-services = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-play-services", version.ref = "coroutines" }

viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "viewmodel-ktx" }

dagger-hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "dagger-hilt" }
dagger-hilt-android-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "dagger-hilt" }
hilt-compiler = { group = "androidx.hilt", name = "hilt-compiler", version.ref = "hilt-compiler" }

compose-compiler = { group = "androidx.compose.compiler", name = "compiler", version.ref = "compose-compiler" }
compose-runtime = { group = "androidx.compose.runtime", name = "runtime", version.ref = "compose" }
compose-material = { group = "androidx.compose.material", name = "material", version.ref = "material" }
compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended", version.ref = "material-icons-extended" }
compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "compose" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "compose" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "compose" }

compose-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version.ref = "compose" }
compose-foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "compose" }
compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4", version.ref = "compose" }

activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "compose-activity" }
compose-paging = { group = "androidx.paging", name = "paging-compose", version.ref = "compose-paging" }
compose-livedata = { group = "androidx.compose.runtime", name = "runtime-livedata", version.ref = "compose-livedata" }
compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "composeMaterial3" }
lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle" }
navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation-compose" }
compose-hilt-navigation = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "compose-hilt-navigation" }
accompanist-flowlayout = { group = "com.google.accompanist", name = "accompanist-flowlayout", version = "accompanist" }
timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }
desugar-jdk-libs = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "desugar-jdk-libs" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
toolbar-compose = { module = "me.onebone:toolbar-compose", version.ref = "onebone" }
mixpanel = { module = "com.mixpanel.android:mixpanel-android", version.ref = "mixpanel" }
play-review = { group = "com.google.android.play", name = "review", version.ref = "play" }
play-review-ktx = { group = "com.google.android.play", name = "review-ktx", version.ref = "play" }
play-app-update = { group = "com.google.android.play", name = "app-update", version.ref = "play" }
play-app-update-ktx = { group = "com.google.android.play", name = "app-update-ktx", version.ref = "play" }
billing = { group = "com.android.billingclient", name = "billing", version.ref = "billing-version" }
play-services-auth = { group = "com.google.android.gms", name = "play-services-auth", version.ref = "play-services-auth" }
one-tap-compose = { module = "com.github.stevdza-san:OneTapCompose", version.ref = "one-tap" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-storage-ktx = { module = "com.google.firebase:firebase-storage-ktx", version.ref = "firebase-storage-ktx" }
firebase-auth-ktx = { module = "com.google.firebase:firebase-auth-ktx", version.ref = "firebase-auth-ktx" }
firebase-database-ktx = { module = "com.google.firebase:firebase-database-ktx", version.ref = "firebase-database-ktx" }
qonversion-sdk = { group = "io.qonversion.android.sdk", name = "sdk", version.ref = "qonversion-sdk" }
accompanist-swiperefresh = { group = "com.google.accompanist", name = "accompanist-swiperefresh", version.ref = "accompanist" }
accompanist-pager = { group = "com.google.accompanist", name = "accompanist-pager", version.ref = "accompanist" }
accompanist-pager-indicators = { group = "com.google.accompanist", name = "accompanist-pager-indicators", version.ref = "accompanist" }
leakcanary-android = { group = "com.squareup.leakcanary", name = "leakcanary-android", version.ref = "leakcanary" }
truth = { group = "com.google.truth", name = "truth", version.ref = "truth" }
arch-core-testing = { group = "androidx.arch.core", name = "core-testing", version.ref = "arch-core-testing" }
lottie-compose = { group = "com.airbnb.android", name = "lottie-compose", version.ref = "lottie" }
datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore" }
paging-runtime = { group = "androidx.paging", name = "paging-runtime", version.ref = "paging" }
easycrop = { group = "io.github.mr0xf00", name = "easycrop", version.ref = "easycrop" }
searchable-dropdown = { group = "com.github.Breens-Mbaka", name = "Searchable-Dropdown-Menu-Jetpack-Compose", version.ref = "searchable-dropdown" }
junit-ext = { group = "androidx.test.ext", name = "junit", version.ref = "junit-ext" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
compose-destinations-animations = { module = "io.github.raamcosta.compose-destinations:animations-core", version.ref = "compose-destinations" }
compose-destinations-ksp = { module = "io.github.raamcosta.compose-destinations:ksp", version.ref = "compose-destinations" }
horizontal-calendar-view = { module = "com.github.JoelKanyi:HorizontalCalendarView", version.ref = "horizontal-calendar-view" }
core-splash-screen = { module = "androidx.core:core-splashscreen", version.ref = "core-splash-screen" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
accompanist-system-ui-controller = { group = "com.google.accompanist", name = "accompanist-systemuicontroller", version.ref = "accompanist" }
squareup-okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
squareup-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
chucker-library = { group = "com.github.chuckerteam.chucker", name = "library", version.ref = "chucker" }
chucker-library-no-op = { group = "com.github.chuckerteam.chucker", name = "library-no-op", version.ref = "chucker" }
android-material = { group = "com.google.android.material", name = "material", version.ref = "android-material" }
sqlDelight-runtime = { module = "com.squareup.sqldelight:runtime", version.ref = "sqlDelight" }
sqlDelight-coroutine = { module = "com.squareup.sqldelight:coroutines-extensions", version.ref = "sqlDelight" }
sqlDelight-android = { module = "com.squareup.sqldelight:android-driver", version.ref = "sqlDelight" }
sqlDelight-native = { module = "com.squareup.sqldelight:native-driver", version.ref = "sqlDelight" }
sqlDelight-JVM = { module = "com.squareup.sqldelight:sqlite-driver", version.ref = "sqlDelight" }

ktor-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktor-serialization = { group = "io.ktor", name = "ktor-client-serialization", version.ref = "ktor" }
ktor-logging = { group = "io.ktor", name = "ktor-client-logging", version.ref = "ktor" }
ktor-android = { group = "io.ktor", name = "ktor-client-android", version.ref = "ktor" }
ktor-ios = { group = "io.ktor", name = "ktor-client-ios", version.ref = "ktor" }
ktor-jvm = { group = "io.ktor", name = "ktor-client-jvm", version.ref = "ktor" }
ktor-content-negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-cio = { group = "io.ktor", name = "ktor-client-cio", version.ref = "ktor" }
ktor-server-auth = { group = "io.ktor", name = "ktor-server-auth", version.ref = "ktor" }
ktor-json = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }


koin-core = { group = "io.insert-koin", name = "koin-core", version.ref = "koin" }
koin-android = { group = "io.insert-koin", name = "koin-android", version.ref = "koin" }
koin-compose = { group = "io.insert-koin", name = "koin-androidx-compose", version.ref = "koin" }

multiplatformSettings = { group = "com.russhwolf", name = "multiplatform-settings-no-arg", version.ref = "multiplatformSettings" }
multiplatformSettingsCoroutines = { group = "com.russhwolf", name = "multiplatform-settings-coroutines", version.ref = "multiplatformSettings" }
napier = { group = "io.github.aakira", name = "napier", version.ref = "napier" }

kotlinxCoroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
kotlinxSerialization = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-core", version.ref = "kotlinxSerialization" }
kotlinxDateTime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinxDateTime" }

[plugins]
android-kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
android-application = { id = "com.android.application", version.ref = "gradle" }
android-library = { id = "com.android.library", version.ref = "gradle" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "dagger-hilt" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
google-services = { id = "com.google.gms.google-services", version.ref = "google-services" }
multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
sqlDelight-plugin = { id = "com.squareup.sqldelight", version.ref = "sqlDelight" }
kotlinX-serialization-plugin = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }